"""Markdown report emitter for screener pipeline runs.

Produces a single ``.md`` file per analysis with a BLUF (Bottom Line Up
Front) at the top, then each pipeline step rendered as its own section so
the reader can drill in.

Section order mirrors the actual graph execution:
  Macro context → IV context → 5 analyst reports → bull/bear debate →
  research-mgr verdict → investment plan → trader proposal →
  3 risk debaters → portfolio-mgr verdict → final decision.

Missing fields are skipped silently — partial state (e.g. a run that
failed mid-pipeline) still produces a useful report.
"""

from __future__ import annotations

import re
from typing import Any


def render_markdown_report(
    *,
    ticker: str,
    trade_date: str,
    state: dict,
    decision: Any,
) -> str:
    """Render a Markdown report for one ticker analysis."""
    final_decision_text = _safe_str(state.get("final_trade_decision"))

    parts: list[str] = []
    parts.append(f"# {ticker} — Trading Agent Report")
    parts.append(f"_Trade date: {trade_date}_\n")

    # --- BLUF ---
    parts.append("## Bottom Line Up Front\n")
    parts.append(f"**Signal**: `{decision}`\n")
    if final_decision_text:
        excerpt = _excerpt(final_decision_text, max_chars=600)
        parts.append("**Portfolio Manager rationale (excerpt)**:\n")
        parts.append("> " + excerpt.replace("\n", "\n> "))
        parts.append("")

    # --- Sections in pipeline execution order ---
    sections: list[tuple[str, str]] = []

    macro = _safe_str(state.get("macro_snapshot"))
    if macro:
        sections.append(("Macro Backdrop (pre-fetched)", macro))

    iv = _safe_str(state.get("iv_snapshot"))
    if iv:
        sections.append(("Implied Volatility Context (pre-fetched)", iv))

    for key, label in (
        ("market_report", "Market Analyst"),
        ("sentiment_report", "Social Media Analyst"),
        ("news_report", "News Analyst"),
        ("fundamentals_report", "Fundamentals Analyst"),
        ("options_report", "Options Analyst"),
    ):
        text = _safe_str(state.get(key))
        if text:
            sections.append((label, text))

    debate = state.get("investment_debate_state") or {}
    if isinstance(debate, dict):
        bull = _safe_str(debate.get("bull_history"))
        bear = _safe_str(debate.get("bear_history"))
        verdict = _safe_str(debate.get("judge_decision"))
        if bull:
            sections.append(("Bull Researcher", bull))
        if bear:
            sections.append(("Bear Researcher", bear))
        if verdict:
            sections.append(("Research Manager Verdict", verdict))

    plan = _safe_str(state.get("investment_plan"))
    if plan:
        sections.append(("Investment Plan", plan))

    # _log_state writes trader_investment_decision; raw state has trader_investment_plan.
    trader_text = _safe_str(
        state.get("trader_investment_decision") or state.get("trader_investment_plan")
    )
    if trader_text:
        sections.append(("Trader Proposal", trader_text))

    risk = state.get("risk_debate_state") or {}
    if isinstance(risk, dict):
        for key, label in (
            ("aggressive_history", "Aggressive Risk Analyst"),
            ("conservative_history", "Conservative Risk Analyst"),
            ("neutral_history", "Neutral Risk Analyst"),
        ):
            text = _safe_str(risk.get(key))
            if text:
                sections.append((label, text))
        risk_verdict = _safe_str(risk.get("judge_decision"))
        if risk_verdict:
            sections.append(("Portfolio Manager Verdict (risk debate)", risk_verdict))

    if final_decision_text:
        sections.append(("Final Trade Decision", final_decision_text))

    for title, content in sections:
        parts.append(f"## {title}\n")
        parts.append(content.strip())
        parts.append("")

    parts.append("---")
    parts.append(
        f"_Generated by TradingAgents screener pipeline. Decision: `{decision}`._"
    )
    return "\n".join(parts) + "\n"


# --- Helpers ---------------------------------------------------------------


def _safe_str(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    return str(value).strip()


def _excerpt(text: str, max_chars: int) -> str:
    """First ``max_chars`` of ``text``, cut at a sentence boundary if possible."""
    if len(text) <= max_chars:
        return text.strip()
    head = text[:max_chars]
    # Prefer cutting at the last sentence-ending punctuation in the window.
    match = re.search(r"^(.*[.!?])\s", head[::-1])  # reverse search trick is overkill;
    last_punct = max(head.rfind("."), head.rfind("!"), head.rfind("?"))
    if last_punct > max_chars * 0.5:
        return head[: last_punct + 1].strip()
    return head.strip() + "…"
