/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by Next.js when the dev server starts.
// It's checked in once so TypeScript resolves Next types before the first
// `next dev` run.
